### ISSUE TITLE
Hit timeout for jpeg callback

### ISSUE THREAD

**Issue by bobeo** [googlesamples/android-Camera2Basic#101]
I make the program to capture still images every N seconds. It runs for a day without any prolem, capturing ~8000 images and then this error pops up:
```
E/RequestThread-0: Hit timeout for jpeg callback!
E/RequestThread-0: Received device exception during capture call: 
                                                                            java.lang.RuntimeException: startPreview failed
                                                                                at android.hardware.Camera.startPreview(Native Method)
                                                                                at android.hardware.camera2.legacy.RequestThreadManager.startPreview(RequestThreadManager.java:286)
                                                                                at android.hardware.camera2.legacy.RequestThreadManager.doPreviewCapture(RequestThreadManager.java:328)
                                                                                at android.hardware.camera2.legacy.RequestThreadManager.-wrap3(RequestThreadManager.java)
                                                                                at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:813)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                at android.os.Looper.loop(Looper.java:203)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
```

My ImageReader is set like this:

`mImageReader = ImageReader.newInstance(finalWidth, finalHeight, mImageFormat, 2 /* images buffered */);`

Does anyone know why the error is there?

Thanks.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
