### ISSUE TITLE
Crash after lockscreen in landscape

### ISSUE THREAD

**Issue by yudikarma** [googlesamples/android-Camera2Basic#144]
`2019-02-22 17:40:02.019 6803-7147/jp.or.crcr.gifu.snowremovesupport E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: jp.or.crcr.gifu.snowremovesupport, PID: 6803
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2020)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:664)
        at jp.or.crcr.gifu.snowremovesupport.ShotActivity_camera2API.createCameraPreviewSession(ShotActivity_camera2API.java:1259)
        at jp.or.crcr.gifu.snowremovesupport.ShotActivity_camera2API.access$500(ShotActivity_camera2API.java:97)
        at jp.or.crcr.gifu.snowremovesupport.ShotActivity_camera2API$2$1.run(ShotActivity_camera2API.java:286)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)`
open camera Activity (set default to landscape) -> lockscreen(with swipe protection screen) -> unlockscreen (in portrait) -> crash

the app will crash . but if not sett swipe for lockcreen. that running perfext.

device  is Xiaomi A1 android N

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
