### ISSUE TITLE
App crashes on image capture

### ISSUE THREAD

**Issue by leapfrog-santosh** [googlesamples/android-Camera2Basic#2]
Though this sample was designed for `Android L developer preview`, I downloaded the sample for `Android L `  from http://developer.android.com/samples/Camera2Basic/. When I click the picture, I get following error

```Java
E/AndroidRuntime﹕ FATAL EXCEPTION: CameraBackground
    Process: com.example.android.camera2basic, PID: 32593
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
            at com.example.android.camera2basic.Camera2BasicFragment$4.process(Camera2BasicFragment.java:269)
            at com.example.android.camera2basic.Camera2BasicFragment$4.onCaptureCompleted(Camera2BasicFragment.java:308)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
            at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```
My testing device is `Nexus 4` and I am running `Android L ` from this `ROM `  http://forum.xda-developers.com/nexus-4/development/lpv-79-mako-port-beta-t2807446.  
P.S. Native Camera App is running smoothly without any hiccups.

**Comment by jbruchanov** [comment]
@leapfrog-santosh 
seems that just calling captureStillPicture() if it's null helps, but who knows if it's the right approach :(
