### ISSUE TITLE
Lock camera timeout when requesting Camera permission

### ISSUE THREAD

**Issue by Tooroop** [googlesamples/android-Camera2Basic#39]
On 6.0 devices when I have camera permissions set everything works fine, but when I have to request the camera permission before using the camera and I click allow I get the following error:

`AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: bla, PID: 22800
                                                                          java.lang.RuntimeException: Unable to resume activity java.lang.RuntimeException: Time out waiting to lock camera opening.
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: java.lang.RuntimeException: Time out waiting to lock camera opening.
                                                                              at ...SellCamera2Fragment.openCamera(SellCamera2Fragment.java:259)
                                                                              at ...SellCamera2Fragment.onResume(SellCamera2Fragment.java:183)
                                                                              at android.support.v4.app.Fragment.performResume(Fragment.java:2005)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
                                                                              at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2052)
                                                                              at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:187)
                                                                              at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:462)
                                                                              at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:451)
                                                                              at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:141)
                                                                              at android.app.Activity.performResume(Activity.java:6336)
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ``

**Comment by reidisaki-goat** [comment]
yeah how do we fix that?

**Comment by ntohill95** [comment]
any update on this bug? Seeing it here too

**Comment by RahulSDeshpande** [comment]
Still waiting..

**Comment by TalViewDev** [comment]
@RahulSDeshpande +1

**Comment by benjlang** [comment]
yay

**Comment by yink-liu** [comment]
maybe twice onresume, permits is 1.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
