### ISSUE TITLE
Lacking privileges to access camera service

### ISSUE THREAD

**Issue by qssq** [googlesamples/android-Camera2Basic#48]
```
                                                Process: com.example.android.camera2basic, PID: 14782
                                                                              java.lang.SecurityException: Lacking privileges to access camera service
                                                                                  at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:108)
                                                                                  at android.hardware.camera2.legacy.CameraDeviceUserShim.connectBinderShim(CameraDeviceUserShim.java:331)
                                                                                  at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:267)
                                                                                  at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:383)
                                                                                  at com.example.android.camera2basic.Camera2BasicFragment.openCamera(Camera2BasicFragment.java:616)
                                                                                  at com.example.android.camera2basic.Camera2BasicFragment.access$000(Camera2BasicFragment.java:74)
                                                                                  at com.example.android.camera2basic.Camera2BasicFragment$1.onSurfaceTextureAvailable(Camera2BasicFragment.java:140)
```

xiaomi 4c china 定制机的问题吗？

**Comment by marcaoas** [comment]
I was having the same problem.
make sure that you are calling the startPreviewingCamera() before you call openCamera.

**Comment by qssq** [comment]
yes

**Comment by panxu** [comment]
have you solve this problem?

**Comment by qssq** [comment]
@panxu  no ..

**Comment by bkraszewski** [comment]
@qssq I had similar issue, in my case that was because of TextureView.SurfaceTextureListener - surface can become available when CameraActivity/Fragment whatever is still in the background - not visible for user.  This code solved issue:

    @Override
    public boolean onSurfaceTextureDestroyed(SurfaceTexture texture) {
        Log.d(TAG, "TextureView.SurfaceTextureListener.onSurfaceTextureDestroyed called");
        setSurfaceTextureListener(null);
        closeCamera();
        return true;
    }
