### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by adnanbinmustafa** [googlesamples/android-Camera2Basic#54]
I have just imported it in android studio using Import An android code samples
 
and after gradle build completed i run the app and getting this null pointer exception. 

please help

`07-28 04:55:24.705 6699-6699/com.example.android.camera2basic E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.android.camera2basic, PID: 6699
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
                                                                                    at com.example.android.camera2basic.Camera2BasicFragment.lockFocus(Camera2BasicFragment.java:778)
                                                                                    at com.example.android.camera2basic.Camera2BasicFragment.takePicture(Camera2BasicFragment.java:769)
                                                                                    at com.example.android.camera2basic.Camera2BasicFragment.onClick(Camera2BasicFragment.java:890)
                                                                                    at android.view.View.performClick(View.java:5204)
                                                                                    at android.view.View$PerformClick.run(View.java:21153)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-28 04:57:47.686 7667-7667/com.example.android.camera2basic E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.android.camera2basic, PID: 7667
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
                                                                                    at com.example.android.camera2basic.Camera2BasicFragment.lockFocus(Camera2BasicFragment.java:777)
                                                                                    at com.example.android.camera2basic.Camera2BasicFragment.takePicture(Camera2BasicFragment.java:768)
                                                                                    at com.example.android.camera2basic.Camera2BasicFragment.onClick(Camera2BasicFragment.java:889)
                                                                                    at android.view.View.performClick(View.java:5204)
                                                                                    at android.view.View$PerformClick.run(View.java:21153)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by adnanbinmustafa** [comment]
``

**Comment by harrysmith88** [comment]
How do you fix it? I'm having the same problem

**Comment by adnanbinmustafa** [comment]
Hello harrymith!

I just restarted my cell phone and problem solved.
