### ISSUE TITLE
Camera not re initialize second time in 5.1.1

### ISSUE THREAD

**Issue by alphaDroid89** [googlesamples/android-Camera2Basic#55]
Hi Team,

Here is my need is, to record a video in number of clips and i merge these clips by using some other third party tools.  

For recording i used setMaxFileSize(<i set 10MB>). So the info listener called when recorder reaches 10MB, I used the below code.

```
@Override
    public void onInfo(MediaRecorder mr, int what, int extra) {

        Log.e("Max file size reached called what", what + "");
        switch (what) {
            case MediaRecorder.MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED:

              mMediaRecorder.reset();
// Here i store the clip in local storage and i start recording for getting the next part, why because once the max file size reached the recorder will be stopped.
                startRecordingVideo();
        }
    }

```

The above code is working fine in Android marshmallow, but when i test the same code in 5.1.1 i got the following error.

```
07-27 20:51:34.167 5810-12582/com.test.video E/CameraDeviceGLThread-0: Received exception on GL render thread: 
                                                                       java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
                                                                           at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
                                                                           at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
                                                                           at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:729)
                                                                           at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:211)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
07-27 20:51:34.167 5810-12582/com.test.video I/CameraDeviceState: Legacy camera service transitioning to state ERROR
07-27 20:51:34.275 5810-5810/com.test.video E/CameraCaptureSession: Session 1: Exception while stopping repeating: 
                                                                    android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
                                                                        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1478)
                                                                        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:677)
                                                                        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:328)
                                                                        at com.test.video.fragments.VideoContentRecording.closePreviewSession(VideoContentRecording.java:871)
                                                                        at com.test.video.fragments.VideoContentRecording.startRecordingVideo(VideoContentRecording.java:812)
                                                                        at com.test.video.fragments.VideoContentRecording.onInfo(VideoContentRecording.java:941)
                                                                        at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1033)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:211)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

Guys, let me know how can i fix this, and please suggest if i'm on the right way or any other solution/possibilities to achieve my need. Thanks in advance.

**Comment by AlejandroHCruz** [comment]
I'm also having this issue on a Lenovo YT3-850F with Android 5.1.1, any news or comments on this?

**Comment by sandeeptengale** [comment]
You got any solution for this? I am also facing same issue on Nexus 4

**Comment by AlejandroHCruz** [comment]
Hi @sandeeptengale, I also managed to pull a workaround for this, sadly I don't remember nor find exactly what it was. What I can say is that my code does have closePreviewSession(); on startPreview().

I'll keep looking and if I find something will comment again here.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
