### ISSUE TITLE
Process hosting the camera service has died unexpectedly

### ISSUE THREAD

**Issue by shyamkumarm** [googlesamples/android-Camera2Basic#89]
android.hardware.camera2.CameraAccessException: Process hosting the camera service has died unexpectedly

  at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onCatchException(CameraBinderDecorator.java:81)
                                                                                            at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:84)
                                                                                            at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                                            at $Proxy1.cancelRequest(Unknown Source)
                                                                                            at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926)
                                                                                            at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
                                                                                            at com.example.android.camera2basic.Camera2BasicFragment.closeCamera(Camera2BasicFragment.java:633)
                                                                                            at com.example.android.camera2basic.Camera2BasicFragment.onPause(Camera2BasicFragment.java:460)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
